/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JToolBar;

/**
 *
 * @author Estudiante
 */
public class MDIInicio extends javax.swing.JFrame {

    /**
     * Creates new form frmInicio
     */
    public MDIInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpdEscritorio = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        btnNuevoF = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnRecaudo = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnSalir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuNuevoF = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpdEscritorio.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jpdEscritorioLayout = new javax.swing.GroupLayout(jpdEscritorio);
        jpdEscritorio.setLayout(jpdEscritorioLayout);
        jpdEscritorioLayout.setHorizontalGroup(
            jpdEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 725, Short.MAX_VALUE)
        );
        jpdEscritorioLayout.setVerticalGroup(
            jpdEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnNuevoF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icono fomulario.png"))); // NOI18N
        btnNuevoF.setToolTipText("Formulario");
        btnNuevoF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevoF.setFocusable(false);
        btnNuevoF.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevoF.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoFActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNuevoF);
        jToolBar1.add(jSeparator2);

        btnRecaudo.setText("Recaudo");
        btnRecaudo.setToolTipText("Recaudo");
        btnRecaudo.setFocusable(false);
        btnRecaudo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRecaudo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnRecaudo);
        jToolBar1.add(jSeparator3);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/exit icono.png"))); // NOI18N
        btnSalir.setToolTipText("Salir");
        btnSalir.setFocusable(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSalir);

        jMenu1.setText("Registro");

        mnuNuevoF.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuNuevoF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icono fomulario.png"))); // NOI18N
        mnuNuevoF.setText("Formulario");
        mnuNuevoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNuevoFActionPerformed(evt);
            }
        });
        jMenu1.add(mnuNuevoF);
        jMenu1.add(jSeparator1);

        mnuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/exit icono.png"))); // NOI18N
        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultas");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpdEscritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpdEscritorio))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void btnNuevoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoFActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void mnuNuevoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNuevoFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuNuevoFActionPerformed

    public JButton getBtnNuevoF() {
        return btnNuevoF;
    }

    public void setBtnNuevoF(JButton btnNuevoF) {
        this.btnNuevoF = btnNuevoF;
    }

    public JButton getBtnRecaudo() {
        return btnRecaudo;
    }

    public void setBtnRecaudo(JButton btnRecaudo) {
        this.btnRecaudo = btnRecaudo;
    }

    public JButton getBtnSalir() {
        return btnSalir;
    }

    public void setBtnSalir(JButton btnSalir) {
        this.btnSalir = btnSalir;
    }

    public JMenu getjMenu1() {
        return jMenu1;
    }

    public void setjMenu1(JMenu jMenu1) {
        this.jMenu1 = jMenu1;
    }

    public JMenu getjMenu2() {
        return jMenu2;
    }

    public void setjMenu2(JMenu jMenu2) {
        this.jMenu2 = jMenu2;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    public JPopupMenu.Separator getjSeparator1() {
        return jSeparator1;
    }

    public void setjSeparator1(JPopupMenu.Separator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    public JToolBar.Separator getjSeparator2() {
        return jSeparator2;
    }

    public void setjSeparator2(JToolBar.Separator jSeparator2) {
        this.jSeparator2 = jSeparator2;
    }

    public JToolBar.Separator getjSeparator3() {
        return jSeparator3;
    }

    public void setjSeparator3(JToolBar.Separator jSeparator3) {
        this.jSeparator3 = jSeparator3;
    }

    public JToolBar getjToolBar1() {
        return jToolBar1;
    }

    public void setjToolBar1(JToolBar jToolBar1) {
        this.jToolBar1 = jToolBar1;
    }

    public JDesktopPane getJpdEscritorio() {
        return jpdEscritorio;
    }

    public void setJpdEscritorio(JDesktopPane jpdEscritorio) {
        this.jpdEscritorio = jpdEscritorio;
    }

    public JMenuItem getMnuNuevoF() {
        return mnuNuevoF;
    }

    public void setMnuNuevoF(JMenuItem mnuNuevoF) {
        this.mnuNuevoF = mnuNuevoF;
    }

    public JMenuItem getMnuSalir() {
        return mnuSalir;
    }

    public void setMnuSalir(JMenuItem mnuSalir) {
        this.mnuSalir = mnuSalir;
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevoF;
    private javax.swing.JButton btnRecaudo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JDesktopPane jpdEscritorio;
    private javax.swing.JMenuItem mnuNuevoF;
    private javax.swing.JMenuItem mnuSalir;
    // End of variables declaration//GEN-END:variables

}
