/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JToolBar;

/**
 *
 * @author Estudiante
 */
public class MDIinicio extends javax.swing.JFrame {

    /**
     * Creates new form MDIinicio
     */
    public MDIinicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jToolBar2 = new javax.swing.JToolBar();
        btnNuevoF = new javax.swing.JButton();
        btnRecaudo = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnConsulta = new javax.swing.JButton();
        btnConsultaBD = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        opc1 = new javax.swing.JMenu();
        mnuNuevoF = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuSalir = new javax.swing.JMenuItem();
        opc2 = new javax.swing.JMenu();
        mnuConsulta = new javax.swing.JMenuItem();
        mnuConsultaBD = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 662, Short.MAX_VALUE)
        );

        btnNuevoF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Icono Formulario.png"))); // NOI18N
        btnNuevoF.setFocusable(false);
        btnNuevoF.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevoF.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(btnNuevoF);

        btnRecaudo.setText("Recaudo");
        btnRecaudo.setFocusable(false);
        btnRecaudo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRecaudo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(btnRecaudo);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/exit icono.png"))); // NOI18N
        btnSalir.setFocusable(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(btnSalir);

        btnConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icono Consulta.png"))); // NOI18N
        btnConsulta.setFocusable(false);
        btnConsulta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsulta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });
        jToolBar2.add(btnConsulta);

        btnConsultaBD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/databases.png"))); // NOI18N
        btnConsultaBD.setFocusable(false);
        btnConsultaBD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsultaBD.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConsultaBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaBDActionPerformed(evt);
            }
        });
        jToolBar2.add(btnConsultaBD);

        opc1.setText("Registro");

        mnuNuevoF.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuNuevoF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Icono Formulario.png"))); // NOI18N
        mnuNuevoF.setText("Nuevo Formulario");
        mnuNuevoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNuevoFActionPerformed(evt);
            }
        });
        opc1.add(mnuNuevoF);
        opc1.add(jSeparator1);

        mnuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/exit icono.png"))); // NOI18N
        mnuSalir.setText("Salir");
        opc1.add(mnuSalir);

        jMenuBar1.add(opc1);

        opc2.setText("Consulta");

        mnuConsulta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icono Consulta.png"))); // NOI18N
        mnuConsulta.setText("Consulta");
        opc2.add(mnuConsulta);

        mnuConsultaBD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/databases.png"))); // NOI18N
        mnuConsultaBD.setText("Consulta BD");
        opc2.add(mnuConsultaBD);

        jMenuBar1.add(opc2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 1107, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(escritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(escritorio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuNuevoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNuevoFActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_mnuNuevoFActionPerformed

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultaActionPerformed

    private void btnConsultaBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaBDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultaBDActionPerformed

    public JButton getBtnConsultaBD() {
        return btnConsultaBD;
    }

    public void setBtnConsultaBD(JButton btnConsultaBD) {
        this.btnConsultaBD = btnConsultaBD;
    }

    
    
    public JMenuItem getMnuConsultaBD() {
        return mnuConsultaBD;
    }

    public void setMnuConsultaBD(JMenuItem mnuConsultaBD) {
        this.mnuConsultaBD = mnuConsultaBD;
    }

    public JButton getBtnConsulta() {
        return btnConsulta;
    }

    public void setBtnConsulta(JButton btnConsulta) {
        this.btnConsulta = btnConsulta;
    }

    public JButton getBtnNuevoF() {
        return btnNuevoF;
    }

    public void setBtnNuevoF(JButton btnNuevoF) {
        this.btnNuevoF = btnNuevoF;
    }

    public JButton getBtnRecaudo() {
        return btnRecaudo;
    }

    public void setBtnRecaudo(JButton btnRecaudo) {
        this.btnRecaudo = btnRecaudo;
    }

    public JButton getBtnSalir() {
        return btnSalir;
    }

    public void setBtnSalir(JButton btnSalir) {
        this.btnSalir = btnSalir;
    }

    public JDesktopPane getEscritorio() {
        return escritorio;
    }

    public void setEscritorio(JDesktopPane escritorio) {
        this.escritorio = escritorio;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    public JPopupMenu.Separator getjSeparator1() {
        return jSeparator1;
    }

    public void setjSeparator1(JPopupMenu.Separator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    public JToolBar getjToolBar2() {
        return jToolBar2;
    }

    public void setjToolBar2(JToolBar jToolBar2) {
        this.jToolBar2 = jToolBar2;
    }

    public JMenuItem getMnuNuevoF() {
        return mnuNuevoF;
    }

    public void setMnuNuevoF(JMenuItem mnuNuevoF) {
        this.mnuNuevoF = mnuNuevoF;
    }

    public JMenuItem getMnuSalir() {
        return mnuSalir;
    }

    public void setMnuSalir(JMenuItem mnuSalir) {
        this.mnuSalir = mnuSalir;
    }

    public JMenu getOpc1() {
        return opc1;
    }

    public void setOpc1(JMenu opc1) {
        this.opc1 = opc1;
    }

    public JMenu getOpc2() {
        return opc2;
    }

    public void setOpc2(JMenu opc2) {
        this.opc2 = opc2;
    }

    public JMenuItem getMnuConsulta() {
        return mnuConsulta;
    }

    public void setMnuConsulta(JMenuItem mnuConsulta) {
        this.mnuConsulta = mnuConsulta;
    }

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsulta;
    private javax.swing.JButton btnConsultaBD;
    private javax.swing.JButton btnNuevoF;
    private javax.swing.JButton btnRecaudo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JMenuItem mnuConsulta;
    private javax.swing.JMenuItem mnuConsultaBD;
    private javax.swing.JMenuItem mnuNuevoF;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JMenu opc1;
    private javax.swing.JMenu opc2;
    // End of variables declaration//GEN-END:variables

}
