/**
 * @author Daniel López Valderrama
 * @author Oscar Gonzalez Soto
 */
package vista;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/*Esta clase es la vista por Default o vista principal del proyecto 
que aloja otras vistas a traves de botones y menus que permiten
manejar la informacion del proyecto*/

/**
 *
 * @author PC
 */

public class vista_MDI extends javax.swing.JFrame {

    /*este dato nos permite manipula un panel para el background del MDI*/
    Panel_MDI fondo = new Panel_MDI();
    
    /**
     *
     */
    public vista_MDI() {
        this.setContentPane(fondo);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        Panel_Iconos = new javax.swing.JPanel();
        btnMembresia = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnConsulta = new javax.swing.JButton();
        btnRecaudo = new javax.swing.JButton();
        btnConsultaBD = new javax.swing.JButton();
        escritorio = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jMenuBar3 = new javax.swing.JMenuBar();
        menu_Membresia = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menu_Consulta = new javax.swing.JMenuItem();
        menu_ConsultaBD = new javax.swing.JMenuItem();
        menu_Recaudo = new javax.swing.JMenuItem();
        menu_Salir = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu6.setText("jMenu6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        Panel_Iconos.setBackground(new java.awt.Color(204, 204, 204));
        Panel_Iconos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Panel_Iconos.setForeground(new java.awt.Color(204, 204, 204));

        btnMembresia.setBackground(new java.awt.Color(204, 204, 204));
        btnMembresia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/membresia.png"))); // NOI18N
        btnMembresia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMembresiaActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(204, 204, 204));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salir.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnConsulta.setBackground(new java.awt.Color(204, 204, 204));
        btnConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/consultar.png"))); // NOI18N
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });

        btnRecaudo.setBackground(new java.awt.Color(204, 204, 204));
        btnRecaudo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/recaudo.png"))); // NOI18N
        btnRecaudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecaudoActionPerformed(evt);
            }
        });

        btnConsultaBD.setBackground(new java.awt.Color(204, 204, 204));
        btnConsultaBD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/databases.png"))); // NOI18N
        btnConsultaBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaBDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_IconosLayout = new javax.swing.GroupLayout(Panel_Iconos);
        Panel_Iconos.setLayout(Panel_IconosLayout);
        Panel_IconosLayout.setHorizontalGroup(
            Panel_IconosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_IconosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(Panel_IconosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalir)
                    .addGroup(Panel_IconosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnRecaudo)
                        .addGroup(Panel_IconosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnConsulta)
                            .addComponent(btnMembresia)
                            .addComponent(btnConsultaBD))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        Panel_IconosLayout.setVerticalGroup(
            Panel_IconosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_IconosLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnMembresia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnConsultaBD)
                .addGap(30, 30, 30)
                .addComponent(btnConsulta)
                .addGap(36, 36, 36)
                .addComponent(btnRecaudo)
                .addGap(18, 18, 18)
                .addComponent(btnSalir)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_Iconos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_Iconos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        escritorio.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 811, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 564, Short.MAX_VALUE)
        );

        jMenuBar3.setBackground(new java.awt.Color(204, 204, 204));
        jMenuBar3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        menu_Membresia.setBackground(new java.awt.Color(255, 255, 102));
        menu_Membresia.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menu_Membresia.setText("Opciones");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_TAB, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu_gym.png"))); // NOI18N
        jMenuItem1.setText("Membresia");
        menu_Membresia.add(jMenuItem1);

        menu_Consulta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_SPACE, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_Consulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu_gym.png"))); // NOI18N
        menu_Consulta.setText("Consulta");
        menu_Consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_ConsultaActionPerformed(evt);
            }
        });
        menu_Membresia.add(menu_Consulta);

        menu_ConsultaBD.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menu_ConsultaBD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu_gym.png"))); // NOI18N
        menu_ConsultaBD.setText("Consulta _BD");
        menu_ConsultaBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_ConsultaBDActionPerformed(evt);
            }
        });
        menu_Membresia.add(menu_ConsultaBD);

        menu_Recaudo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menu_Recaudo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu_gym.png"))); // NOI18N
        menu_Recaudo.setText("Recaudo");
        menu_Recaudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_RecaudoActionPerformed(evt);
            }
        });
        menu_Membresia.add(menu_Recaudo);

        menu_Salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        menu_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salir.png"))); // NOI18N
        menu_Salir.setText("Salir");
        menu_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_SalirActionPerformed(evt);
            }
        });
        menu_Membresia.add(menu_Salir);

        jMenuBar3.add(menu_Membresia);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(escritorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 65, Short.MAX_VALUE))
                    .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_SalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_SalirActionPerformed

    private void menu_ConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_ConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_ConsultaActionPerformed

    private void btnMembresiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMembresiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMembresiaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultaActionPerformed

    private void btnRecaudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecaudoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRecaudoActionPerformed

    private void menu_RecaudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_RecaudoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_RecaudoActionPerformed

    private void btnConsultaBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaBDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultaBDActionPerformed

    private void menu_ConsultaBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_ConsultaBDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_ConsultaBDActionPerformed

    /**
     *
     * @return
     */
    public JDesktopPane getEscritorio() {
        return escritorio;
    }

    /**
     *
     * @param escritorio
     */
    public void setEscritorio(JDesktopPane escritorio) {
        this.escritorio = escritorio;
    }

    /**
     *
     * @return
     */
    public JButton getBtnConsultaBD() {
        return btnConsultaBD;
    }

    /**
     *
     * @param btnConsultaBD
     */
    public void setBtnConsultaBD(JButton btnConsultaBD) {
        this.btnConsultaBD = btnConsultaBD;
    }

    /**
     *
     * @return
     */
    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     *
     * @param jScrollPane1
     */
    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    /**
     *
     * @return
     */
    public JMenuItem getMenu_ConsultaBD() {
        return menu_ConsultaBD;
    }

    /**
     *
     * @param menu_ConsultaBD
     */
    public void setMenu_ConsultaBD(JMenuItem menu_ConsultaBD) {
        this.menu_ConsultaBD = menu_ConsultaBD;
    }

    /**
     *
     * @return
     */
    public JMenuItem getMenu_Recaudo() {
        return menu_Recaudo;
    }

    /**
     *
     * @param menu_Recaudo
     */
    public void setMenu_Recaudo(JMenuItem menu_Recaudo) {
        this.menu_Recaudo = menu_Recaudo;
    }

    /**
     *
     * @return
     */
    public JButton getBtnRecaudo() {
        return btnRecaudo;
    }

    /**
     *
     * @param btnRecaudo
     */
    public void setBtnRecaudo(JButton btnRecaudo) {
        this.btnRecaudo = btnRecaudo;
    }

    /**
     *
     * @return
     */
    public Panel_MDI getFondo() {
        return fondo;
    }

    /**
     *
     * @param fondo
     */
    public void setFondo(Panel_MDI fondo) {
        this.fondo = fondo;
    }

    /**
     *
     * @return
     */
    public JPanel getPanel_Iconos() {
        return Panel_Iconos;
    }

    /**
     *
     * @param Panel_Iconos
     */
    public void setPanel_Iconos(JPanel Panel_Iconos) {
        this.Panel_Iconos = Panel_Iconos;
    }

    /**
     *
     * @return
     */
    public JButton getBtnConsulta() {
        return btnConsulta;
    }

    /**
     *
     * @param btnConsulta
     */
    public void setBtnConsulta(JButton btnConsulta) {
        this.btnConsulta = btnConsulta;
    }

    /**
     *
     * @return
     */
    public JButton getBtnMembresia() {
        return btnMembresia;
    }

    /**
     *
     * @param btnMembresia
     */
    public void setBtnMembresia(JButton btnMembresia) {
        this.btnMembresia = btnMembresia;
    }

    /**
     *
     * @return
     */
    public JButton getBtnSalir() {
        return btnSalir;
    }

    /**
     *
     * @param btnSalir
     */
    public void setBtnSalir(JButton btnSalir) {
        this.btnSalir = btnSalir;
    }

    /**
     *
     * @return
     */
    public JMenu getjMenu1() {
        return jMenu1;
    }

    /**
     *
     * @param jMenu1
     */
    public void setjMenu1(JMenu jMenu1) {
        this.jMenu1 = jMenu1;
    }

    /**
     *
     * @return
     */
    public JMenu getjMenu2() {
        return jMenu2;
    }

    /**
     *
     * @param jMenu2
     */
    public void setjMenu2(JMenu jMenu2) {
        this.jMenu2 = jMenu2;
    }

    /**
     *
     * @return
     */
    public JMenu getjMenu3() {
        return jMenu3;
    }

    /**
     *
     * @param jMenu3
     */
    public void setjMenu3(JMenu jMenu3) {
        this.jMenu3 = jMenu3;
    }

    /**
     *
     * @return
     */
    public JMenu getjMenu4() {
        return jMenu4;
    }

    /**
     *
     * @param jMenu4
     */
    public void setjMenu4(JMenu jMenu4) {
        this.jMenu4 = jMenu4;
    }

    /**
     *
     * @return
     */
    public JMenu getjMenu6() {
        return jMenu6;
    }

    /**
     *
     * @param jMenu6
     */
    public void setjMenu6(JMenu jMenu6) {
        this.jMenu6 = jMenu6;
    }

    /**
     *
     * @return
     */
    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    /**
     *
     * @param jMenuBar1
     */
    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    /**
     *
     * @return
     */
    public JMenuBar getjMenuBar2() {
        return jMenuBar2;
    }

    /**
     *
     * @param jMenuBar2
     */
    public void setjMenuBar2(JMenuBar jMenuBar2) {
        this.jMenuBar2 = jMenuBar2;
    }

    /**
     *
     * @return
     */
    public JMenuBar getjMenuBar3() {
        return jMenuBar3;
    }

    /**
     *
     * @param jMenuBar3
     */
    public void setjMenuBar3(JMenuBar jMenuBar3) {
        this.jMenuBar3 = jMenuBar3;
    }

    /**
     *
     * @return
     */
    public JMenuItem getjMenuItem1() {
        return jMenuItem1;
    }

    /**
     *
     * @param jMenuItem1
     */
    public void setjMenuItem1(JMenuItem jMenuItem1) {
        this.jMenuItem1 = jMenuItem1;
    }

    /**
     *
     * @return
     */
    public JPanel getjPanel1() {
        return jPanel1;
    }

    /**
     *
     * @param jPanel1
     */
    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    /**
     *
     * @return
     */
    public JMenuItem getMenu_Consulta() {
        return menu_Consulta;
    }

    /**
     *
     * @param menu_Consulta
     */
    public void setMenu_Consulta(JMenuItem menu_Consulta) {
        this.menu_Consulta = menu_Consulta;
    }

    /**
     *
     * @return
     */
    public JMenu getMenu_Membresia() {
        return menu_Membresia;
    }

    /**
     *
     * @param menu_Membresia
     */
    public void setMenu_Membresia(JMenu menu_Membresia) {
        this.menu_Membresia = menu_Membresia;
    }

    /**
     *
     * @return
     */
    public JMenuItem getMenu_Salir() {
        return menu_Salir;
    }

    /**
     *
     * @param menu_Salir
     */
    public void setMenu_Salir(JMenuItem menu_Salir) {
        this.menu_Salir = menu_Salir;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_Iconos;
    private javax.swing.JButton btnConsulta;
    private javax.swing.JButton btnConsultaBD;
    private javax.swing.JButton btnMembresia;
    private javax.swing.JButton btnRecaudo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menu_Consulta;
    private javax.swing.JMenuItem menu_ConsultaBD;
    private javax.swing.JMenu menu_Membresia;
    private javax.swing.JMenuItem menu_Recaudo;
    private javax.swing.JMenuItem menu_Salir;
    // End of variables declaration//GEN-END:variables

    
    /*esta clase permite utilizar un background que se ajuste automaticamente 
    al tamaño de la ventana MDI*/
    class Panel_MDI extends JPanel{
        private Image imagen_MDI;
        @Override
        public void paint(Graphics g){
            imagen_MDI = new ImageIcon(getClass().getResource("/img/gym_MDI.jpeg")).getImage();
            g.drawImage(imagen_MDI,0,0,getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
}
