/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author FAMILIA
 */
public class frmJIVentanaCB extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmJIVentanaCB
     */
    public frmJIVentanaCB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPnl = new javax.swing.JTabbedPane();
        pnlDatosPaciente = new javax.swing.JPanel();
        lblTelefono = new javax.swing.JLabel();
        lblFechaNacimiento = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        dateFechaNac = new com.toedter.calendar.JDateChooser();
        pnlDatosConsulta = new javax.swing.JPanel();
        lblDesc = new javax.swing.JLabel();
        cmbServicio = new javax.swing.JComboBox<>();
        lblTipoS = new javax.swing.JLabel();
        pnlExamen = new javax.swing.JPanel();
        lblExamen = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        cmbExamen = new javax.swing.JComboBox<>();
        txtDescripcion = new javax.swing.JTextField();
        lblFechaConsulta = new javax.swing.JLabel();
        pnlConsultaM = new javax.swing.JPanel();
        lblConsultaMedica = new javax.swing.JLabel();
        lblTipoConsultaMedica = new javax.swing.JLabel();
        cmbConsultaM = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        dateFechaConsulta = new com.toedter.calendar.JDateChooser();
        pnlHospitalizacion = new javax.swing.JPanel();
        lblHospitalizacion = new javax.swing.JLabel();
        lblTipoHab = new javax.swing.JLabel();
        cmbHosp = new javax.swing.JComboBox<>();
        lblDiasHosp = new javax.swing.JLabel();
        spinnerDias = new javax.swing.JSpinner();
        pnlTablaRegistro = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistro = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        tabbedPnl.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N

        lblTelefono.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblTelefono.setText("Telefono:");

        lblFechaNacimiento.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblFechaNacimiento.setText("Fecha de nacimiento:");

        txtNombre.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtTelefono.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblNombre.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblNombre.setText("Nombre:");

        javax.swing.GroupLayout pnlDatosPacienteLayout = new javax.swing.GroupLayout(pnlDatosPaciente);
        pnlDatosPaciente.setLayout(pnlDatosPacienteLayout);
        pnlDatosPacienteLayout.setHorizontalGroup(
            pnlDatosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosPacienteLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(pnlDatosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosPacienteLayout.createSequentialGroup()
                        .addComponent(lblFechaNacimiento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDatosPacienteLayout.createSequentialGroup()
                        .addGroup(pnlDatosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(lblTelefono))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlDatosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(441, Short.MAX_VALUE))
        );
        pnlDatosPacienteLayout.setVerticalGroup(
            pnlDatosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosPacienteLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(pnlDatosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaNacimiento)
                    .addComponent(dateFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(237, Short.MAX_VALUE))
        );

        tabbedPnl.addTab("Datos Paciente", pnlDatosPaciente);

        lblDesc.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblDesc.setText("Descripción:");

        cmbServicio.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbServicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Exámen de Laboratorio", "Consulta Médica", "Hospitalización" }));

        lblTipoS.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblTipoS.setText("Tipo de Servicio:");

        lblExamen.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblExamen.setText("Examen");

        lblCategoria.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblCategoria.setText("Categoria: ");

        cmbExamen.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbExamen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "Otro" }));
        cmbExamen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbExamenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlExamenLayout = new javax.swing.GroupLayout(pnlExamen);
        pnlExamen.setLayout(pnlExamenLayout);
        pnlExamenLayout.setHorizontalGroup(
            pnlExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExamenLayout.createSequentialGroup()
                .addGroup(pnlExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlExamenLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(cmbExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlExamenLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(lblExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        pnlExamenLayout.setVerticalGroup(
            pnlExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExamenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblExamen)
                .addGap(18, 18, 18)
                .addGroup(pnlExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoria)
                    .addComponent(cmbExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        txtDescripcion.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDescripcion.setToolTipText("");
        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });

        lblFechaConsulta.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblFechaConsulta.setText("Fecha de la consulta:");

        lblConsultaMedica.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblConsultaMedica.setText("Consulta Médica");

        lblTipoConsultaMedica.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblTipoConsultaMedica.setText("Tipo de consulta:");

        cmbConsultaM.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbConsultaM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General", "Especialista", "Otro" }));
        cmbConsultaM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbConsultaMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlConsultaMLayout = new javax.swing.GroupLayout(pnlConsultaM);
        pnlConsultaM.setLayout(pnlConsultaMLayout);
        pnlConsultaMLayout.setHorizontalGroup(
            pnlConsultaMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultaMLayout.createSequentialGroup()
                .addGroup(pnlConsultaMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConsultaMLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblTipoConsultaMedica, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbConsultaM, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlConsultaMLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(lblConsultaMedica, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlConsultaMLayout.setVerticalGroup(
            pnlConsultaMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultaMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConsultaMedica)
                .addGap(18, 18, 18)
                .addGroup(pnlConsultaMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoConsultaMedica)
                    .addComponent(cmbConsultaM, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRegistrar.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnRegistrar.setText("Registrar");

        lblHospitalizacion.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblHospitalizacion.setText("Hospitalización");

        lblTipoHab.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblTipoHab.setText("Tipo Habitación");

        cmbHosp.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbHosp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estandar", "Semi-privada", "Privada", "Otro" }));
        cmbHosp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbHospActionPerformed(evt);
            }
        });

        lblDiasHosp.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblDiasHosp.setText("Dias Hospitalizado:");

        javax.swing.GroupLayout pnlHospitalizacionLayout = new javax.swing.GroupLayout(pnlHospitalizacion);
        pnlHospitalizacion.setLayout(pnlHospitalizacionLayout);
        pnlHospitalizacionLayout.setHorizontalGroup(
            pnlHospitalizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHospitalizacionLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlHospitalizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHospitalizacionLayout.createSequentialGroup()
                        .addGroup(pnlHospitalizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlHospitalizacionLayout.createSequentialGroup()
                                .addComponent(lblDiasHosp, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(spinnerDias, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlHospitalizacionLayout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(lblHospitalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlHospitalizacionLayout.createSequentialGroup()
                        .addComponent(lblTipoHab, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbHosp, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );
        pnlHospitalizacionLayout.setVerticalGroup(
            pnlHospitalizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHospitalizacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblHospitalizacion)
                .addGap(18, 18, 18)
                .addGroup(pnlHospitalizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoHab)
                    .addComponent(cmbHosp, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlHospitalizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiasHosp)
                    .addComponent(spinnerDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout pnlDatosConsultaLayout = new javax.swing.GroupLayout(pnlDatosConsulta);
        pnlDatosConsulta.setLayout(pnlDatosConsultaLayout);
        pnlDatosConsultaLayout.setHorizontalGroup(
            pnlDatosConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosConsultaLayout.createSequentialGroup()
                .addGroup(pnlDatosConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosConsultaLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(lblTipoS)
                        .addGap(29, 29, 29)
                        .addComponent(cmbServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlDatosConsultaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlDatosConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDatosConsultaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(pnlDatosConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pnlExamen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pnlConsultaM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(pnlHospitalizacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(22, 22, 22)
                        .addGroup(pnlDatosConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDatosConsultaLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblDesc)
                            .addGroup(pnlDatosConsultaLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(dateFechaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblFechaConsulta)
                            .addGroup(pnlDatosConsultaLayout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(btnRegistrar)))
                        .addGap(3722, 3722, 3722)))
                .addGap(32, 32, 32))
        );
        pnlDatosConsultaLayout.setVerticalGroup(
            pnlDatosConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosConsultaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlDatosConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoS)
                    .addComponent(cmbServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(pnlDatosConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosConsultaLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(lblFechaConsulta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateFechaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDatosConsultaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlExamen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnlDatosConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosConsultaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(lblDesc)
                        .addGap(18, 18, 18)
                        .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegistrar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlDatosConsultaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlConsultaM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlHospitalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(20, Short.MAX_VALUE))))
        );

        tabbedPnl.addTab("Datos Consulta", pnlDatosConsulta);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tblRegistro.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 255, 255)));
        tblRegistro.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tblRegistro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha Factura", "ID paciente", "Nombre", "Categoria", "Codigo Servicio", "Valor a Pagar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRegistro);

        javax.swing.GroupLayout pnlTablaRegistroLayout = new javax.swing.GroupLayout(pnlTablaRegistro);
        pnlTablaRegistro.setLayout(pnlTablaRegistroLayout);
        pnlTablaRegistroLayout.setHorizontalGroup(
            pnlTablaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTablaRegistroLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(155, 155, 155))
        );
        pnlTablaRegistroLayout.setVerticalGroup(
            pnlTablaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlTablaRegistroLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tabbedPnl.addTab("Registro", pnlTablaRegistro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(tabbedPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(487, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(tabbedPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(248, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void cmbExamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbExamenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbExamenActionPerformed

    private void cmbConsultaMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbConsultaMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbConsultaMActionPerformed

    private void cmbHospActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbHospActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbHospActionPerformed

    public JButton getBtnRegistrar() {
        return btnRegistrar;
    }

    public void setBtnRegistrar(JButton btnRegistrar) {
        this.btnRegistrar = btnRegistrar;
    }

    public JComboBox<String> getCmbConsultaM() {
        return cmbConsultaM;
    }

    public void setCmbConsultaM(JComboBox<String> cmbConsultaM) {
        this.cmbConsultaM = cmbConsultaM;
    }

    public JComboBox<String> getCmbExamen() {
        return cmbExamen;
    }

    public void setCmbExamen(JComboBox<String> cmbExamen) {
        this.cmbExamen = cmbExamen;
    }

    public JComboBox<String> getCmbHosp() {
        return cmbHosp;
    }

    public void setCmbHosp(JComboBox<String> cmbHosp) {
        this.cmbHosp = cmbHosp;
    }

    public JComboBox<String> getCmbServicio() {
        return cmbServicio;
    }

    public void setCmbServicio(JComboBox<String> cmbServicio) {
        this.cmbServicio = cmbServicio;
    }

    public JDateChooser getDateFechaConsulta() {
        return dateFechaConsulta;
    }

    public void setDateFechaConsulta(JDateChooser dateFechaConsulta) {
        this.dateFechaConsulta = dateFechaConsulta;
    }

    public JDateChooser getDateFechaNac() {
        return dateFechaNac;
    }

    public void setDateFechaNac(JDateChooser dateFechaNac) {
        this.dateFechaNac = dateFechaNac;
    }

    public JPanel getjPanel5() {
        return jPanel5;
    }

    public void setjPanel5(JPanel jPanel5) {
        this.jPanel5 = jPanel5;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JLabel getLblCategoria() {
        return lblCategoria;
    }

    public void setLblCategoria(JLabel lblCategoria) {
        this.lblCategoria = lblCategoria;
    }

    public JLabel getLblConsultaMedica() {
        return lblConsultaMedica;
    }

    public void setLblConsultaMedica(JLabel lblConsultaMedica) {
        this.lblConsultaMedica = lblConsultaMedica;
    }

    public JLabel getLblDesc() {
        return lblDesc;
    }

    public void setLblDesc(JLabel lblDesc) {
        this.lblDesc = lblDesc;
    }

    public JLabel getLblDiasHosp() {
        return lblDiasHosp;
    }

    public void setLblDiasHosp(JLabel lblDiasHosp) {
        this.lblDiasHosp = lblDiasHosp;
    }

    public JLabel getLblExamen() {
        return lblExamen;
    }

    public void setLblExamen(JLabel lblExamen) {
        this.lblExamen = lblExamen;
    }

    public JLabel getLblFechaConsulta() {
        return lblFechaConsulta;
    }

    public void setLblFechaConsulta(JLabel lblFechaConsulta) {
        this.lblFechaConsulta = lblFechaConsulta;
    }

    public JLabel getLblFechaNacimiento() {
        return lblFechaNacimiento;
    }

    public void setLblFechaNacimiento(JLabel lblFechaNacimiento) {
        this.lblFechaNacimiento = lblFechaNacimiento;
    }

    public JLabel getLblHospitalizacion() {
        return lblHospitalizacion;
    }

    public void setLblHospitalizacion(JLabel lblHospitalizacion) {
        this.lblHospitalizacion = lblHospitalizacion;
    }

    public JLabel getLblNombre() {
        return lblNombre;
    }

    public void setLblNombre(JLabel lblNombre) {
        this.lblNombre = lblNombre;
    }

    public JLabel getLblTelefono() {
        return lblTelefono;
    }

    public void setLblTelefono(JLabel lblTelefono) {
        this.lblTelefono = lblTelefono;
    }

    public JLabel getLblTipoConsultaMedica() {
        return lblTipoConsultaMedica;
    }

    public void setLblTipoConsultaMedica(JLabel lblTipoConsultaMedica) {
        this.lblTipoConsultaMedica = lblTipoConsultaMedica;
    }

    public JLabel getLblTipoHab() {
        return lblTipoHab;
    }

    public void setLblTipoHab(JLabel lblTipoHab) {
        this.lblTipoHab = lblTipoHab;
    }

    public JLabel getLblTipoS() {
        return lblTipoS;
    }

    public void setLblTipoS(JLabel lblTipoS) {
        this.lblTipoS = lblTipoS;
    }

    public JPanel getPnlConsultaM() {
        return pnlConsultaM;
    }

    public void setPnlConsultaM(JPanel pnlConsultaM) {
        this.pnlConsultaM = pnlConsultaM;
    }

    public JPanel getPnlDatosConsulta() {
        return pnlDatosConsulta;
    }

    public void setPnlDatosConsulta(JPanel pnlDatosConsulta) {
        this.pnlDatosConsulta = pnlDatosConsulta;
    }

    public JPanel getPnlDatosPaciente() {
        return pnlDatosPaciente;
    }

    public void setPnlDatosPaciente(JPanel pnlDatosPaciente) {
        this.pnlDatosPaciente = pnlDatosPaciente;
    }

    public JPanel getPnlExamen() {
        return pnlExamen;
    }

    public void setPnlExamen(JPanel pnlExamen) {
        this.pnlExamen = pnlExamen;
    }

    public JPanel getPnlHospitalizacion() {
        return pnlHospitalizacion;
    }

    public void setPnlHospitalizacion(JPanel pnlHospitalizacion) {
        this.pnlHospitalizacion = pnlHospitalizacion;
    }

    public JPanel getPnlTablaRegistro() {
        return pnlTablaRegistro;
    }

    public void setPnlTablaRegistro(JPanel pnlTablaRegistro) {
        this.pnlTablaRegistro = pnlTablaRegistro;
    }

    public JSpinner getSpinnerDias() {
        return spinnerDias;
    }

    public void setSpinnerDias(JSpinner spinnerDias) {
        this.spinnerDias = spinnerDias;
    }

    public JTabbedPane getTabbedPnl() {
        return tabbedPnl;
    }

    public void setTabbedPnl(JTabbedPane tabbedPnl) {
        this.tabbedPnl = tabbedPnl;
    }

    public JTable getTblRegistro() {
        return tblRegistro;
    }

    public void setTblRegistro(JTable tblRegistro) {
        this.tblRegistro = tblRegistro;
    }

    public JTextField getTxtDescripcion() {
        return txtDescripcion;
    }

    public void setTxtDescripcion(JTextField txtDescripcion) {
        this.txtDescripcion = txtDescripcion;
    }

    public JTextField getTxtNombre() {
        return txtNombre;
    }

    public void setTxtNombre(JTextField txtNombre) {
        this.txtNombre = txtNombre;
    }

    public JTextField getTxtTelefono() {
        return txtTelefono;
    }

    public void setTxtTelefono(JTextField txtTelefono) {
        this.txtTelefono = txtTelefono;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbConsultaM;
    private javax.swing.JComboBox<String> cmbExamen;
    private javax.swing.JComboBox<String> cmbHosp;
    private javax.swing.JComboBox<String> cmbServicio;
    private com.toedter.calendar.JDateChooser dateFechaConsulta;
    private com.toedter.calendar.JDateChooser dateFechaNac;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblConsultaMedica;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblDiasHosp;
    private javax.swing.JLabel lblExamen;
    private javax.swing.JLabel lblFechaConsulta;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JLabel lblHospitalizacion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTipoConsultaMedica;
    private javax.swing.JLabel lblTipoHab;
    private javax.swing.JLabel lblTipoS;
    private javax.swing.JPanel pnlConsultaM;
    private javax.swing.JPanel pnlDatosConsulta;
    private javax.swing.JPanel pnlDatosPaciente;
    private javax.swing.JPanel pnlExamen;
    private javax.swing.JPanel pnlHospitalizacion;
    private javax.swing.JPanel pnlTablaRegistro;
    private javax.swing.JSpinner spinnerDias;
    private javax.swing.JTabbedPane tabbedPnl;
    private javax.swing.JTable tblRegistro;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
