/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JToolBar;

/**
 *
 * @author FAMILIA
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        btnNuevoServicio = new javax.swing.JButton();
        btnConsulta = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnSalir = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        registroMenu = new javax.swing.JMenu();
        mnuNuevoS = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuSalida = new javax.swing.JMenuItem();
        consultaMenu = new javax.swing.JMenu();
        mnuConsulta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setForeground(new java.awt.Color(0, 0, 0));

        jToolBar1.setFloatable(false);

        btnNuevoServicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icono Servicio.png"))); // NOI18N
        btnNuevoServicio.setFocusable(false);
        btnNuevoServicio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevoServicio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnNuevoServicio);

        btnConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icono Consulta.png"))); // NOI18N
        btnConsulta.setFocusable(false);
        btnConsulta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsulta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnConsulta);
        jToolBar1.add(jSeparator2);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/exit icono.png"))); // NOI18N
        btnSalir.setFocusable(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnSalir);

        registroMenu.setMnemonic('f');
        registroMenu.setText("Registro");

        mnuNuevoS.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuNuevoS.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        mnuNuevoS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icono Servicio.png"))); // NOI18N
        mnuNuevoS.setMnemonic('o');
        mnuNuevoS.setText("Nuevo Registro");
        mnuNuevoS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNuevoSActionPerformed(evt);
            }
        });
        registroMenu.add(mnuNuevoS);
        registroMenu.add(jSeparator1);

        mnuSalida.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuSalida.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        mnuSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/exit icono.png"))); // NOI18N
        mnuSalida.setMnemonic('x');
        mnuSalida.setText("Salir");
        mnuSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalidaActionPerformed(evt);
            }
        });
        registroMenu.add(mnuSalida);

        menuBar.add(registroMenu);

        consultaMenu.setMnemonic('e');
        consultaMenu.setText("Consulta");

        mnuConsulta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuConsulta.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        mnuConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icono Consulta.png"))); // NOI18N
        mnuConsulta.setMnemonic('t');
        mnuConsulta.setText("Consultar");
        consultaMenu.add(mnuConsulta);

        menuBar.add(consultaMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 1102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalidaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuSalidaActionPerformed

    private void mnuNuevoSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNuevoSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuNuevoSActionPerformed

    public JButton getBtnConsulta() {
        return btnConsulta;
    }

    public void setBtnConsulta(JButton btnConsulta) {
        this.btnConsulta = btnConsulta;
    }

    public JButton getBtnNuevoServicio() {
        return btnNuevoServicio;
    }

    public void setBtnNuevoServicio(JButton btnNuevoServicio) {
        this.btnNuevoServicio = btnNuevoServicio;
    }

    public JButton getBtnSalir() {
        return btnSalir;
    }

    public void setBtnSalir(JButton btnSalir) {
        this.btnSalir = btnSalir;
    }

    public JMenu getConsultaMenu() {
        return consultaMenu;
    }

    public void setConsultaMenu(JMenu consultaMenu) {
        this.consultaMenu = consultaMenu;
    }

    public JDesktopPane getEscritorio() {
        return escritorio;
    }

    public void setEscritorio(JDesktopPane escritorio) {
        this.escritorio = escritorio;
    }

    public JPopupMenu.Separator getjSeparator1() {
        return jSeparator1;
    }

    public void setjSeparator1(JPopupMenu.Separator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    public JToolBar.Separator getjSeparator2() {
        return jSeparator2;
    }

    public void setjSeparator2(JToolBar.Separator jSeparator2) {
        this.jSeparator2 = jSeparator2;
    }

    public JToolBar getjToolBar1() {
        return jToolBar1;
    }

    public void setjToolBar1(JToolBar jToolBar1) {
        this.jToolBar1 = jToolBar1;
    }
    
    public void setMenuBar(JMenuBar menuBar) {
        this.menuBar = menuBar;
    }

    public JMenuItem getMnuConsulta() {
        return mnuConsulta;
    }

    public void setMnuConsulta(JMenuItem mnuConsulta) {
        this.mnuConsulta = mnuConsulta;
    }

    public JMenuItem getMnuNuevoS() {
        return mnuNuevoS;
    }

    public void setMnuNuevoS(JMenuItem mnuNuevoS) {
        this.mnuNuevoS = mnuNuevoS;
    }

    public JMenuItem getMnuSalida() {
        return mnuSalida;
    }

    public void setMnuSalida(JMenuItem mnuSalida) {
        this.mnuSalida = mnuSalida;
    }

    public JMenu getRegistroMenu() {
        return registroMenu;
    }

    public void setRegistroMenu(JMenu registroMenu) {
        this.registroMenu = registroMenu;
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsulta;
    private javax.swing.JButton btnNuevoServicio;
    private javax.swing.JButton btnSalir;
    private javax.swing.JMenu consultaMenu;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnuConsulta;
    private javax.swing.JMenuItem mnuNuevoS;
    private javax.swing.JMenuItem mnuSalida;
    private javax.swing.JMenu registroMenu;
    // End of variables declaration//GEN-END:variables

}
