/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JToolBar;

/**
 *
 * @author Estudiante
 */
public class MDIinicio extends javax.swing.JFrame {

    /**
     * Creates new form MDIinicio
     */
    public MDIinicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jToolBar2 = new javax.swing.JToolBar();
        btnNuevoF = new javax.swing.JButton();
        btnRecaudo = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        opcRegistro = new javax.swing.JMenu();
        mnuNuevoF = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuSalir = new javax.swing.JMenuItem();
        opcConsulta = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        btnNuevoF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icono fomulario.png"))); // NOI18N
        btnNuevoF.setFocusable(false);
        btnNuevoF.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevoF.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(btnNuevoF);

        btnRecaudo.setText("Recaudo");
        btnRecaudo.setFocusable(false);
        btnRecaudo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRecaudo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(btnRecaudo);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/exit icono.png"))); // NOI18N
        btnSalir.setFocusable(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(btnSalir);

        opcRegistro.setText("Registro");

        mnuNuevoF.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuNuevoF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icono fomulario.png"))); // NOI18N
        mnuNuevoF.setText("Nuevo Formulario");
        mnuNuevoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNuevoFActionPerformed(evt);
            }
        });
        opcRegistro.add(mnuNuevoF);
        opcRegistro.add(jSeparator1);

        mnuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/exit icono.png"))); // NOI18N
        mnuSalir.setText("Salir");
        opcRegistro.add(mnuSalir);

        jMenuBar1.add(opcRegistro);

        opcConsulta.setText("Consulta");
        jMenuBar1.add(opcConsulta);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(escritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(escritorio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuNuevoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNuevoFActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_mnuNuevoFActionPerformed

    /**
     * @param args the command line arguments
     */

    public JButton getBtnNuevoF() {
        return btnNuevoF;
    }

    public void setBtnNuevoF(JButton btnNuevoF) {
        this.btnNuevoF = btnNuevoF;
    }

    public JButton getBtnRecaudo() {
        return btnRecaudo;
    }

    public void setBtnRecaudo(JButton btnRecaudo) {
        this.btnRecaudo = btnRecaudo;
    }

    public JButton getBtnSalir() {
        return btnSalir;
    }

    public void setBtnSalir(JButton btnSalir) {
        this.btnSalir = btnSalir;
    }

    public JDesktopPane getEscritorio() {
        return escritorio;
    }

    public void setEscritorio(JDesktopPane escritorio) {
        this.escritorio = escritorio;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    public JPopupMenu.Separator getjSeparator1() {
        return jSeparator1;
    }

    public void setjSeparator1(JPopupMenu.Separator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    public JToolBar getjToolBar2() {
        return jToolBar2;
    }

    public void setjToolBar2(JToolBar jToolBar2) {
        this.jToolBar2 = jToolBar2;
    }

    public JMenuItem getMnuNuevoF() {
        return mnuNuevoF;
    }

    public void setMnuNuevoF(JMenuItem mnuNuevoF) {
        this.mnuNuevoF = mnuNuevoF;
    }

    public JMenuItem getMnuSalir() {
        return mnuSalir;
    }

    public void setMnuSalir(JMenuItem mnuSalir) {
        this.mnuSalir = mnuSalir;
    }

    public JMenu getOpcConsulta() {
        return opcConsulta;
    }

    public void setOpcConsulta(JMenu opcConsulta) {
        this.opcConsulta = opcConsulta;
    }

    public JMenu getOpcRegistro() {
        return opcRegistro;
    }

    /**
     * @param args the command line arguments
     */
    public void setOpcRegistro(JMenu opcRegistro) {
        this.opcRegistro = opcRegistro;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevoF;
    private javax.swing.JButton btnRecaudo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JMenuItem mnuNuevoF;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JMenu opcConsulta;
    private javax.swing.JMenu opcRegistro;
    // End of variables declaration//GEN-END:variables

}
