/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JToolBar;

/**
 *
 * @author FAMILIA
 */
public class MDIInicio extends javax.swing.JFrame {

    /**
     * Creates new form MDIInicio
     */
    public MDIInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        escritorio = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        btnBMI = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        opcBMI = new javax.swing.JMenuItem();
        opcSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        opcRegistros = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IMC");

        escritorio.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        desktopPane.add(escritorio);
        escritorio.setBounds(0, 50, 640, 460);

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setFloatable(false);

        btnBMI.setBackground(new java.awt.Color(255, 255, 255));
        btnBMI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/_Bmi.png"))); // NOI18N
        btnBMI.setFocusable(false);
        btnBMI.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBMI.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnBMI);

        desktopPane.add(jToolBar1);
        jToolBar1.setBounds(0, 0, 640, 50);

        jMenuBar1.setBackground(new java.awt.Color(153, 153, 153));

        jMenu1.setBackground(new java.awt.Color(153, 153, 153));
        jMenu1.setText("Herramientas");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        opcBMI.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opcBMI.setBackground(new java.awt.Color(255, 255, 255));
        opcBMI.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        opcBMI.setForeground(new java.awt.Color(0, 0, 0));
        opcBMI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/_Bmi.png"))); // NOI18N
        opcBMI.setText("Calcular IMC");
        opcBMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcBMIActionPerformed(evt);
            }
        });
        jMenu1.add(opcBMI);

        opcSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opcSalir.setBackground(new java.awt.Color(255, 255, 255));
        opcSalir.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        opcSalir.setForeground(new java.awt.Color(0, 0, 0));
        opcSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/exit.png"))); // NOI18N
        opcSalir.setText("Salir");
        jMenu1.add(opcSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(153, 153, 153));
        jMenu2.setText("Consultar");
        jMenu2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        opcRegistros.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opcRegistros.setBackground(new java.awt.Color(255, 255, 255));
        opcRegistros.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        opcRegistros.setForeground(new java.awt.Color(0, 0, 0));
        opcRegistros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/registros.png"))); // NOI18N
        opcRegistros.setText("Registros");
        jMenu2.add(opcRegistros);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcBMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcBMIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcBMIActionPerformed

    /**
     * @return 
     */

    public JButton getBtnBMI() {
        return btnBMI;
    }

    public void setBtnBMI(JButton btnBMI) {
        this.btnBMI = btnBMI;
    }

    public JDesktopPane getDesktopPane() {
        return desktopPane;
    }

    public void setDesktopPane(JDesktopPane desktopPane) {
        this.desktopPane = desktopPane;
    }

    public JDesktopPane getEscritorio() {
        return escritorio;
    }

    public void setEscritorio(JDesktopPane escritorio) {
        this.escritorio = escritorio;
    }

    public JMenu getjMenu1() {
        return jMenu1;
    }

    public void setjMenu1(JMenu jMenu1) {
        this.jMenu1 = jMenu1;
    }

    public JMenu getjMenu2() {
        return jMenu2;
    }

    public void setjMenu2(JMenu jMenu2) {
        this.jMenu2 = jMenu2;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    public JToolBar getjToolBar1() {
        return jToolBar1;
    }

    public void setjToolBar1(JToolBar jToolBar1) {
        this.jToolBar1 = jToolBar1;
    }

    public JMenuItem getOpcBMI() {
        return opcBMI;
    }

    public void setOpcBMI(JMenuItem opcBMI) {
        this.opcBMI = opcBMI;
    }

    public JMenuItem getOpcRegistros() {
        return opcRegistros;
    }

    public void setOpcRegistros(JMenuItem opcRegistros) {
        this.opcRegistros = opcRegistros;
    }

    public JMenuItem getOpcSalir() {
        return opcSalir;
    }

    /**
     * @param opcSalir
     */
    public void setOpcSalir(JMenuItem opcSalir) {
        this.opcSalir = opcSalir;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBMI;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem opcBMI;
    private javax.swing.JMenuItem opcRegistros;
    private javax.swing.JMenuItem opcSalir;
    // End of variables declaration//GEN-END:variables

}
